# Generated by Django 4.2.3 on 2023-07-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Make',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Mobile_Number',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Required_Part',
            new_name='required_part',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='State',
            new_name='state',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=2561),
            preserve_default=False,
        ),
    ]
