# Generated by Django 4.2.3 on 2023-07-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_contact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.FileField(default=None, max_length=256, null=True, upload_to='image/'),
        ),
    ]
