# Generated by Django 4.2.3 on 2023-07-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_contact_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
