# Generated by Django 4.2.3 on 2023-07-25 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_contact_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='contact',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
