# Generated by Django 4.2.3 on 2023-07-29 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_contact_date_time_alter_contact_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 17, 9, 19, 782566, tzinfo=datetime.timezone.utc)),
        ),
    ]
