# Generated by Django 4.2.3 on 2023-07-30 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_alter_contact_date_time_alter_contact_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 30, 23, 3, 25, 972423, tzinfo=datetime.timezone.utc)),
        ),
    ]
