# Generated by Django 4.2.4 on 2023-08-08 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_alter_contact_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 22, 5, 37, 183151, tzinfo=datetime.timezone.utc)),
        ),
    ]
