# Generated by Django 4.2.4 on 2023-08-08 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_alter_contact_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 22, 12, 12, 333516, tzinfo=datetime.timezone.utc)),
        ),
    ]
