# Generated by Django 4.2.4 on 2023-08-14 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_alter_contact_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 21, 12, 47, 415736, tzinfo=datetime.timezone.utc)),
        ),
    ]
