# Generated by Django 4.2.4 on 2023-08-14 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_alter_contact_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 21, 24, 33, 642622, tzinfo=datetime.timezone.utc)),
        ),
    ]
